spring:
  application:
    name: job-journaler

  r2dbc:
    name: job_journaler
    password: root
    username: root
    url: r2dbc:mariadb://mariadb:3306/job_journaler

  sql:
    init:
      mode: always # Always initialize the database on startup

logging:
  level:
    org.example.jobjournaler: debug

management:
  endpoints:
    web:
      exposure:
        include: health
