spring:
  application:
    name: angular-demo

  r2dbc:
    name: demo
    password: root
    username: root
    url: r2dbc:mariadb://mariadb:3306/demo

  sql:
    init:
      mode: always # Always initialize the database on startup

logging:
  level:
    org.example.angulardemo: debug
