# Spring Boot App
@base_url = http://localhost:8080


@products_url = {{base_url}}/products
@users_url = {{base_url}}/users

## Product API
### GET request to get all products for a certain user
GET {{products_url}}/1

### POST request to create a product
POST {{products_url}}/1
Content-Type: application/json

{
  "userId": 1,
  "name": "test",
  "description": "tester"
}

### PUT request to update a product
PUT {{products_url}}/1/3
Content-Type: application/json

{
  "id": 3,
  "userId": 1,
  "name": "testamon",
  "description": "tester"
}

### DELETE request to delete a product
DELETE {{products_url}}/1/3
Content-Type: application/json

## User API

### GET request to get user by email
GET {{users_url}}
X-Forwarded-Email: jp_brasser@hotmail.com

### get it
GET localhost:9000/api/products/1

### delete some?
DELETE localhost:9000/api/products/1/1
